version: '3.8'

services:
  advisor-db:
    image: mysql:5.7
    container_name: advisor_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: Advisor
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  advisor-app:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: advisor_app
    restart: always
    depends_on:
      - advisor-db
    ports:
      - "3000:3000"
    environment:
      DB_HOST: advisor-db
      DB_USER: user
      DB_PASSWORD: userpassword
      DB_NAME: Advisor
    volumes:
      - ./src:/usr/src/app

networks:
  default:
    driver: bridge